# Generated by Django 4.2.10 on 2024-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_rename_status_card_status_url_alter_card_status_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="status_freq",
            field=models.IntegerField(default=10),
        ),
    ]
