# Generated by Django 4.2.10 on 2024-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_card_status_freq"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="docker_container_name",
            field=models.URLField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="card",
            name="docker_container_status",
            field=models.URLField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="card",
            name="docker_container_uptime",
            field=models.URLField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="card",
            name="docker_server_url",
            field=models.URLField(default="", max_length=150),
        ),
    ]
