# Generated by Django 4.2.10 on 2024-02-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_card_docker_container_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="docker_env",
            field=models.CharField(default="1", max_length=2),
        ),
    ]
