# Generated by Django 5.1.6 on 2025-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_card_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="image",
            field=models.CharField(default="arch-linux.png", max_length=100),
        ),
    ]
