# Generated by Django 5.1.6 on 2025-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_card_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="icon_form_table",
            field=models.BooleanField(default=False),
        ),
    ]
